filter:
  excluded_paths: [vendor/*, res/*, doc/*]

tools:
  external_code_coverage:
    enabled: true
    timeout: 600
  php_code_sniffer:
    enabled: true
    filter:
      excluded_paths: [vendor/*, res/*, doc/*]
  php_mess_detector:
    enabled: true
    filter:
      excluded_paths: [vendor/*, res/*, doc/*]
  php_cpd:
    enabled: true
    excluded_dirs: [venodr/*, res/*, doc/*]
    filter:
      excluded_paths: [venodr/*, res/*, doc/*]
