language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - php composer.phar install --dev

script:
  - phpunit --configuration phpunit.travis.xml --bootstrap phpunit.bootstrap.php

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover log/coverage/coverage.xml
